# Visvalingam-Whyatt polygon simplification configuration
algorithm: visvalingam
min_vertices: 10
batch_size: 400000
# Resolution steps can be left empty to be calculated automatically
# based on the vertex_count and min_vertices
resolution_steps: []